#create namespace avalanche
apiVersion: v1
kind: Namespace
metadata:
  name: avalanche
spec:
  finalizers:
  - kubernetes
---
#create deployment avalanche
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: avalanche
  namespace: avalanche
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      name: avalanche
  template:
    metadata:
      labels:
        name: avalanche
    spec:
      hostNetwork: true
      containers:
      - name: pg-avalanche
        image: quay.io/freshtracks.io/avalanche:latest
        args:
        - "--metric-count=100000"
        - "--series-count=5000"
        - "--port=9030"
        ports:
        - containerPort: 9030
---
#create service avalanche-svc
apiVersion: v1
kind: Service
metadata:
  name: avalanche-svc
  namespace: avalanche
  labels:
    name: avalanche
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    # the port that this service should serve on
    - port: 9030
      targetPort: 9030
      name: http-avalanche
  type: ClusterIP
  clusterIP: None
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: avalanche
---
#create service avalanche-svc
apiVersion: v1
kind: Service
metadata:
  name: avalanche-np-svc
  namespace: avalanche
  labels:
    name: avalanche
spec:
  ports:
    # the port that this service should serve on
    - port: 9030
      targetPort: 9030
      name: http-avalanche
  type: NodePort
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: avalanche
